spring:
  profiles:
    active:
    - dev

---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-caozhi-dev
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-caozhi-test